services:
  localstack:
    image: localstack/localstack:3.7.0
    container_name: pix_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - EAGER_SERVICE_LOADING=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: pix_app
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT_URL=http://localstack:4566
      - DYNAMODB_TABLE_NAME=pix_transactions_store
    depends_on:
      localstack:
        condition: service_healthy
